<?php

namespace App\Models\Errors;

use Illuminate\Database\Eloquent\Model;

class JsError extends Model
{
	protected $casts = [
		'exception' => 'array',
		'vm' => 'array',
	];

	public function error(){
		return $this->morphOne(Error::class, 'errorable');
	}

	public function delete() {
		$this->error->delete();
		return parent::delete(); // TODO: Change the autogenerated stub
	}
}
